-- Clientes
INSERT INTO CLIENT (CPF, EMAIL, NAME, PASSWORD) VALUES ('345.654.268.98', 'ana@gmail.com', 'Ana Laura', 'NDIHDUG');
INSERT INTO CLIENT (CPF, EMAIL, NAME, PASSWORD) VALUES ('123.654.908.99', 'larissa@gmail.com', 'Larissa Gomes', 'SADNADKJ');
INSERT INTO CLIENT (CPF, EMAIL, NAME, PASSWORD) VALUES ('331.604.218.76', 'pedrocarvalho@gmail.com', 'Pedro Carvalho', 'JFGIEHRI');
INSERT INTO CLIENT (CPF, EMAIL, NAME, PASSWORD) VALUES ('912.086.245.35', 'pedroreis@gmail.com', 'Pedro Reis', 'DFNIJGEIRGN');
INSERT INTO CLIENT (CPF, EMAIL, NAME, PASSWORD) VALUES ('122.432.123.45', 'tarcila@gmail.com', 'Tarcila Fernanda', 'OIEWIRHFD');

-- Livros
INSERT INTO BOOK (ID,  AUTHOR, CATEGORY, COVERURL, DESCRIPTION, IS_RELEASE, PRICE, RATE, RELEASE_DATE, STOCK, TITLE) VALUES (1, 'Stephen King', 'Terror', 'https://images-na.ssl-images-amazon.com/images/I/51z0s3GcvwL._SX346_BO1,204,203,200_.jpg', 'Durante as férias de 1958, em uma pacata cidadezinha chamada Derry, um grupo de sete amigos começa a ver coisas estranhas. Um conta que viu um palhaço, outro que viu uma múmia. Finalmente, acabam descobrindo que estavam todos vendo a mesma coisa: um ser sobrenatural e maligno que pode assumir várias formas. É assim que Bill, Beverly, Eddie, Ben, Richie, Mike e Stan enfrentam a Coisa pela primeira vez.', 0, 59.90, 5, '1986-09-15', 2, 'It: A coisa');
INSERT INTO BOOK (ID,  AUTHOR, CATEGORY, COVERURL, DESCRIPTION, IS_RELEASE, PRICE, RATE, RELEASE_DATE, STOCK, TITLE) VALUES (2, 'Sun Tzu', 'Não ficção', 'https://images-na.ssl-images-amazon.com/images/I/31QzwYLvuCL._SX313_BO1,204,203,200_.jpg', 'O que faz de um tratado militar, escrito por volta de 500 a.C., manter-se atual a ponto de ser publicado praticamente no mundo todo até os dias de hoje? Você verá que, em A arte da guerra, as estratégias transmitidas pelo general chinês Sun Tzu carregam um profundo conhecimento da natureza humana. Elas transcendem os limites dos campos de batalha e alcançam o contexto das pequenas ou grandes lutas cotidianas, sejam em ambientes competitivos – como os do mundo corporativo – sejam nos desafios internos, em que temos de encarar nossas próprias dificuldades. Se você não conhece a si mesmo nem o inimigo, sucumbirá a todas as batalhas. Sun Tzu', 0, 19.75, 4, '2008-04-07', 5, 'A Arte da Guerra');
INSERT INTO BOOK (ID,  AUTHOR, CATEGORY, COVERURL, DESCRIPTION, IS_RELEASE, PRICE, RATE, RELEASE_DATE, STOCK, TITLE) VALUES (3, 'Robert C. Martin', 'Computação', 'https://images-na.ssl-images-amazon.com/images/I/41aHzYSXZkL._SX380_BO1,204,203,200_.jpg', 'Mesmo um código ruim pode funcionar. Mas se ele não for limpo, pode acabar com uma empresa de desenvolvimento. Perdem-se a cada ano horas incontáveis e recursos importantes devido a um código mal escrito. Mas não precisa ser assim.O renomado especialista em software, Robert C. Martin, apresenta um paradigma revolucionário com Código limpo: Habilidades Práticas do Agile Software.', 0, 61.75, 0, '2009-09-08', 4.3, 'Código limpo: Habilidades práticas do Agile Software');