INSERT INTO CLIENT (CPF, EMAIL, NAME, PASSWORD) VALUES ('345.654.268.98', 'ana@gmail.com', 'Ana Laura', 'NDIHDUG');
INSERT INTO CLIENT (CPF, EMAIL, NAME, PASSWORD) VALUES ('123.654.908.99', 'larissa@gmail.com', 'Larissa Gomes', 'SADNADKJ');
INSERT INTO CLIENT (CPF, EMAIL, NAME, PASSWORD) VALUES ('331.604.218.76', 'pedrocarvalho@gmail.com', 'Pedro Carvalho', 'JFGIEHRI');
INSERT INTO CLIENT (CPF, EMAIL, NAME, PASSWORD) VALUES ('912.086.245.35', 'pedroreis@gmail.com', 'Pedro Reis', 'DFNIJGEIRGN');
INSERT INTO CLIENT (CPF, EMAIL, NAME, PASSWORD) VALUES ('122.432.123.45', 'tarcila@gmail.com', 'Tarcila Fernanda', 'OIEWIRHFD');